
version: '3.9'

services:
  db:
    image: postgis/postgis
    container_name: postgis_db
    environment:
      POSTGRES_DB: gisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
